### ISSUE TITLE
Vaimo Composer patches dependency - is it needed?

### ISSUE THREAD

**Issue by madsnorgaard** [OS2Forms/os2forms#16]
Hi Bellcom and Andriy,

What is the main reason for having this package as dependency - https://github.com/OS2Forms/os2forms/blob/739673bb479c0f8f54c403e84c3bd335329d6af0/composer.json#L35

It introduces the following issue: https://github.com/vaimo/composer-patches/issues/85

We already use the [cweagans/composer-patches](https://github.com/cweagans/composer-patches) for this functionality.

Should I submit a PR?

**Comment by andriyun** [comment]
Hi @madsnorgaard 

The main reason to have `vaimo/composer-patches` package is to get the ability to apply patches defined on the package level.
> Patches can be defined both on project and on package level in package config or separate JSON file. 

Package `cweagans/composer-patches` doesn't cover this feature.

**Comment by madsnorgaard** [comment]
Thank you for the explanation @andriyun - i will close the issue at this point.
