### ISSUE TITLE
hook_webform_admin_third_party_settings_form_alter() giver fejl ved gem af globale webformular indstillinger

### ISSUE THREAD

**Issue by madsnorgaard** [OS2Forms/os2forms#17]
https://github.com/OS2Forms/os2forms/blob/739673bb479c0f8f54c403e84c3bd335329d6af0/os2forms.module#L40

For at ændre på en lang række globale indstillinger for webformularer, skal man gå til admin/structure/webform/config

Problematikken lige nu, er at man ikke kan gemme siden, da der er blevet indført en bug i OS2forms-modulet, som gør at dropdown ovenfor, OS2forms, har en default værdi sat til "anden", hvilket ikke er valid og siden kan derfor ikke gemmes.

**Comment by skifter** [comment]
Er dette stadig aktuelt eller kan de lukkes ? @madsnorgaard

**Comment by madsnorgaard** [comment]
Hej @skifter 

Den er fortsat aktuel vil jeg mene - en mindre bug, men kan være svær at gennemskue for slutbrugeren.

**Comment by skifter** [comment]
In the os2forms settings you are not allowed to save due to the default value in this setting is empty. 

If you set it to "ingen" then you can save wuthout having to type something. 
The default for empty should be "ingen" not "andet"

**Comment by stanbellcom** [comment]
pushed a fix for it
